
library(osmar) # loads osmar libarary which downloads data from openstreetmap as puts it into a dataframe
library(rgeos) # geometry library get area in metres squared
library(rgdal) # projection linrary to transform projection
 library(rCharts) # 
 library(rjson)
 require(plyr)
 library(RColorBrewer)
 library(httr)
 library(maptools)
 require(RGoogleDocs)
 library(devtools)
library(RCurl)
library(knitr) # create html webpage from this code
 library(sp)# library for spatial analysis - can plot 'graphs'/maps of sp objects
library(rgbif)
 library(SortableHTMLTables)



system("rm /home/tim/github/localtivate/Rscripts/localtivate.geojson")
system("rm /home/tim/github/localtivate/Rscripts/localtivate.shp")
system("rm /home/tim/github/localtivate/Rscripts/localtivate_survey.shp")
system("rm /home/tim/github/localtivate/Rscripts/localtivate_survey.geojson")
system("wget -O /home/tim/github/localtivate/Rscripts/localtivate.osm \"http://overpass-api.de/api/interpreter?data=way[%22localtivate%22]%2855.30570111642547,-5.3887939453125,56.74669909639952,-2.49114990234375%29;out%20body;%3E;out%20skel;\"")
system("ogr2ogr -f GeoJSON /home/tim/github/localtivate/Rscripts/localtivate.geojson /home/tim/github/localtivate/Rscripts/localtivate.osm multipolygons")
json_orchards = '/home/tim/github/localtivate/Rscripts/localtivate.geojson'

json_orchards <- fromJSON(paste(readLines(json_orchards), collapse=""))

system("ogr2ogr -f \"ESRI Shapefile\" /home/tim/github/localtivate/Rscripts/localtivate.shp /home/tim/github/localtivate/Rscripts/localtivate.osm multipolygons")

x <- readShapeSpatial("/home/tim/github/localtivate/Rscripts/localtivate.shp")

survey <- read.csv("duddingston_survey.csv", check.names= FALSE)

survey$name <- survey$'Unique reference number  (your initials and a number)'

merged <- merge(x=x@data, y=survey, by.x='localtivat', by.y='name', all.x=TRUE)
merged2 <- merged[,c("localtivat","osm_way_id","leisure", "Location of the space", "Which of the following categories best describes the space?", "What natural features are present?","What man-made features are present?","Terrain","Exposure and Orientation", "Current uses","Does this space have an official name? How do local people usually refer to it?", "Accessibility","History and prior uses of site","Comments and Extras", "Unique reference number  (your initials and a number)", "Potential future uses")]
  

correct.ordering <- match(x@data$localtivat, merged2$localtivat)
x@data <- merged2[correct.ordering, ]
cbind(x@data$localtivat, merged2$name[correct.ordering])
writeSpatialShape(x, fn="/home/tim/github/localtivate/Rscripts/localtivate_survey")
 writeOGR(x, 'localtivate_survey.geojson','localtivate_survey', driver='GeoJSON')

system("ogr2ogr -f GeoJSON /home/tim/github/localtivate/Rscripts/localtivate_survey.geojson  /home/tim/github/localtivate/Rscripts/localtivate_survey.shp")

# json_orchards2 = '/home/tim/github/localtivate/Rscripts/localtivate_survey.geojson'

# json_orchards2 <- fromJSON(paste(readLines(json_orchards2), collapse=""))

# json_orchards2$features <- lapply(json_orchards2$features, function(properties){within(properties, {
# popup = iconv(whisker::whisker.render(
# '<b> Name: {{properties.name}} </b><br>
 #       <b>Other OpenStreetMap tags: </b> {{properties.other_tags}} <br>
 # <b>Number of volunteers: </b> {{properties.number_of_}} <br>
#  <b>Number of trees: </b> {{properties.number_of_2}} <br>
# <b>Active management: </b> {{properties.active_man}} <br>'    
# ), from = 'latin1', to = 'UTF-8')
# })
# })

